### ISSUE TITLE
example does not work

### ISSUE THREAD

**Issue by grimm26** [bazaarvoice/cloudformation-ruby-dsl#44]
```
% ./cloudformation-ruby-script.rb expand
./cloudformation-ruby-script.rb:176:in `block in <main>': undefined method `equals' for #<TemplateDSL:0x007f8c9aa87720> (NoMethodError)
        from /Users/mkeisler/git/github/cloudformation-ruby-dsl/lib/cloudformation-ruby-dsl/cfntemplate.rb:260:in `instance_eval'
        from /Users/mkeisler/git/github/cloudformation-ruby-dsl/lib/cloudformation-ruby-dsl/cfntemplate.rb:260:in `initialize'
        from /Users/mkeisler/git/github/cloudformation-ruby-dsl/lib/cloudformation-ruby-dsl/cfntemplate.rb:293:in `initialize'
        from /Users/mkeisler/git/github/cloudformation-ruby-dsl/lib/cloudformation-ruby-dsl/cfntemplate.rb:284:in `new'
        from /Users/mkeisler/git/github/cloudformation-ruby-dsl/lib/cloudformation-ruby-dsl/cfntemplate.rb:284:in `template'
        from ./cloudformation-ruby-script.rb:24:in `<main>'
```

**Comment by jonaf** [comment]
This is a silly typo on my part. It should be `equal`. I'll update it, but in the meantime, you can modify the template yourself to use the correct method name.

**Comment by grimm26** [comment]
ok, FYI that typo is in multiple places.
